version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./project/backend/src:/usr/src/app
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27019:27017"
